-- MySQL Script generated by MySQL Workbench
-- Fri Nov 11 22:23:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_evento` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `id` INT NOT NULL,
  `latitud` FLOAT NOT NULL,
  `longitud` FLOAT NULL,
  `eventocol` VARCHAR(45) NULL,
  `tipo_evento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_evento_id`),
  INDEX `fk_evento_tipo_evento1_idx` (`tipo_evento_id` ASC) VISIBLE,
  CONSTRAINT `fk_evento_tipo_evento1`
    FOREIGN KEY (`tipo_evento_id`)
    REFERENCES `mydb`.`tipo_evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`informe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`informe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`informe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resumen` VARCHAR(1000) NULL,
  `estado_alerta` VARCHAR(45) NULL,
  `evento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `evento_id`),
  UNIQUE INDEX `id_informe_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_informe_evento_idx` (`evento_id` ASC) VISIBLE,
  CONSTRAINT `fk_informe_evento`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE,
  UNIQUE INDEX `id_user_type_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `mail` VARCHAR(60) NOT NULL,
  `foto` VARCHAR(5000) NULL,
  `tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_usuario_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_usuarios_tipo_usuario1_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `mydb`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`informe_has_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`informe_has_usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`informe_has_usuarios` (
  `informe_id` INT NOT NULL,
  `informe_evento_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`informe_id`, `informe_evento_id`, `usuarios_id`),
  INDEX `fk_informe_has_usuarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_informe_has_usuarios_informe1_idx` (`informe_id` ASC, `informe_evento_id` ASC) VISIBLE,
  CONSTRAINT `fk_informe_has_usuarios_informe1`
    FOREIGN KEY (`informe_id` , `informe_evento_id`)
    REFERENCES `mydb`.`informe` (`id` , `evento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informe_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
